# Create Article - Press Release Category
press_release2 = Article.new(title: "AMMAN Announces Its Commitment to The Copper Mark for Responsible Copper Production", category: @cat2)
press_release2.image.attach(io: Rails.root.join("public/images/news/articles-news.jpeg").open, filename: "articles-news.jpeg")
press_release2.content = %q{
	<p>JAKARTA, 26 September 2023 - PT Amman Mineral Nusa Tenggara (AMMAN) signed a Letter of Commitment (LoC) with The Copper Mark, the first and only assurance framework for copper, created to demonstrate responsible production practices and the industry’s contribution to the United Nations Sustainable Development Goals, or SDGs.</p>
	<p>AMMAN’s President Director, Rachmat Makkasau, stated that the association with The Copper Mark describes the company’s commitment to implementing good mining practices in every aspect of its operations. “As one of Indonesia’s largest copper producers, AMMAN’s vision is to create a legacy of best in everything we do. Our legacy is not only for the company, but also for surrounding communities and environment. This vision is our motivation to sign the LoC with The Copper Mark,” stated Rachmat.</p>
	<p>To receive The Copper Mark participating copper producer sites, including AMMAN’s, are assessed against 32 responsible production criteria. The criteria are defined by the Risk Readiness Assessment created and owned by the Responsible Minerals Initiative. The Risk Readiness Assessment covers the core expectations for responsible production across all major environmental, social and governance issue areas. Once the participating site can demonstrate, through an independent third-party assessment, that they fully or partially meet all 32 criteria, the Copper Mark is awarded. For any areas that are partially met, the site must implement an improvement plan within 12 months of the assessment.</p>
	<p>Founded and developed by the International Copper Association, since December 2019, The Copper Mark has been incorporated as an independent and multi-stakeholder organization.  The organization is governed by its Board of Directors and Multi-stakeholder Advisory Council including civil society and human rights experts.</p>
	}
Mobility.with_locale(:id) {
press_release2.title = "AMMAN Mengumumkan Komitmennya terhadap Merek Tembaga untuk Produksi Tembaga yang Bertanggung Jawab"
press_release2.content = %q{
	<p>JAKARTA, 26 September 2023 - PT Amman Mineral Nusa Tenggara (AMMAN) menandatangani Letter of Commitment (LoC) dengan The Copper Mark, kerangka jaminan pertama dan satu-satunya untuk tembaga, yang dibuat untuk menunjukkan praktik produksi yang bertanggung jawab dan kontribusi industri terhadap PBB Tujuan Pembangunan Berkelanjutan, atau SDGs.</p>
	<p>Direktur Utama AMMAN, Rachmat Makkasau, menyatakan, kerja sama dengan The Copper Mark menggambarkan komitmen perusahaan dalam menerapkan praktik penambangan yang baik di setiap aspek operasionalnya. “Sebagai salah satu produsen tembaga terbesar di Indonesia, visi AMMAN adalah menciptakan warisan terbaik dalam segala hal yang kami lakukan. Warisan kami tidak hanya untuk perusahaan, tetapi juga untuk masyarakat dan lingkungan sekitar. Visi inilah yang menjadi motivasi kami untuk menandatangani LoC dengan The Copper Mark,” kata Rachmat.</p>
	<p>Untuk menerima The Copper Mark, lokasi produsen tembaga yang berpartisipasi, termasuk AMMAN, dinilai berdasarkan 32 kriteria produksi yang bertanggung jawab. Kriterianya ditentukan oleh Penilaian Kesiapan Risiko yang dibuat dan dimiliki oleh Responsible Minerals Initiative. Penilaian Kesiapan Risiko mencakup harapan inti produksi yang bertanggung jawab di seluruh bidang permasalahan utama lingkungan, sosial, dan tata kelola. Setelah lokasi yang berpartisipasi dapat menunjukkan, melalui penilaian pihak ketiga yang independen, bahwa mereka sepenuhnya atau sebagian memenuhi 32 kriteria, Tanda Tembaga diberikan. Untuk setiap area yang terpenuhi sebagian, lokasi harus menerapkan rencana perbaikan dalam waktu 12 bulan setelah penilaian.</p>
	<p>Didirikan dan dikembangkan oleh International Copper Association, sejak Desember 2019, The Copper Mark telah berbadan hukum sebagai organisasi independen dan multi-stakeholder. Organisasi ini dipimpin oleh Dewan Direksi dan Dewan Penasihat Multi-pemangku kepentingan termasuk masyarakat sipil dan pakar hak asasi manusia.</p>
	}
}
press_release2.published_date = DateTime.strptime('09/26/2023 1:46 AM', '%m/%d/%Y %I:%M %p')
press_release2.save
puts "Create Press Release: #{press_release2.title}"
